[tool.poetry]
name = "carstino"
version = "0.2.5"
description = ""
authors = ["Waket Zheng <waketzheng@gmail.com>"]

# Use `poetry-plugin-pypi-mirror` instead (python pip_conf.py --poetry)
#[[tool.poetry.source]]
#name = "tx"
#url = "https://mirrors.cloud.tencent.com/pypi/simple/"
#default = true

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
fast-dev-cli = {extras = ["all"], version = "*"}
asyncur = "^0.5.0"

[tool.ruff]
line-length = 88
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "__pycache__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "*.bak",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]

[tool.mypy]
ignore_missing_imports = true
warn_no_return = false
exclude = [
    "^fabfile\\.py$",  # TOML's double-quoted strings require escaping backslashes
    'two\.pyi$',  # but TOML's single-quoted strings do not
    '^\.venv',
    '\.bak',
]
[[tool.mypy.overrides]]
module = "*.migrations.*"
ignore_errors = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
